org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
# Parallel Tooling API sync, supported from Gradle 9.4.
org.gradle.tooling.parallel=true

android.useAndroidX=true
android.nonTransitiveRClass=true

kotlin.code.style=official
